### PR TITLE
Fix/division by zero in l10n br account invoice costs ratio wizard

### PR DESCRIPTION
**Pull request by cmsalmeida**

### CODE REVIEW

**Comment by danimaribeiro** [comment]
I see no problem to check division by zero.
But do you know why amount_total is being passed zero? Didn't test yet

**Comment by cmsalmeida** [comment]
it happened when invoice had no lines, it's a remote chance but we should check it any way preventing the error.

**Comment by danimaribeiro** [comment]
LGTM

**Comment by mileo** [comment]
LGTM: No tests

**Comment by danimaribeiro** [comment]
:+1:

**Comment by cmsalmeida** [comment]
TKS!!

**Pull request merged**
